version: '3.7'
services:
  db:
    image: mongo:latest
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
      - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
      - APP_MONGO_HOST=${MONGO_HOST}
      - APP_MONGO_USER=${APP_MONGO_USER}
      - APP_MONGO_PASS=${APP_MONGO_PASS}
      - APP_MONGO_DB=${APP_MONGO_DB}
    volumes:
      - type: bind
        source: ./data
        target: /data/db
      - type: bind
        source: ./scripts
        target: /docker-entrypoint-initdb.d
